### ISSUE TITLE
Change to allow WebCamIframe to be larger

### ISSUE THREAD

**Issue by prawnz** [jneilliii/OctoPrint-WebcamIframe#16]
Any chance to have a setting to make the frame larger? I am using Shinobi with it and it is working great just not big enough to contain just enough height for 1 screen in shinobi

![image](https://user-images.githubusercontent.com/3827044/107109238-7cdb2400-6879-11eb-8259-280274ceb357.png)

**Comment by jneilliii** [comment]
I notice you're using Themeify, you might be able to adjust the size of the iframe using it's advanced customization options. The selector in question that you want to adjust is `iframe#webcam_container`.

**Comment by prawnz** [comment]
> I notice you're using Themeify, you might be able to adjust the size of the iframe using it's advanced customization options. The selector in question that you want to adjust is `iframe#webcam_container`.

Yup that works for now. Thanks for the tip
