### ISSUE TITLE
Unable to embed twitch stream

### ISSUE THREAD

**Issue by DKAY15** [jneilliii/OctoPrint-WebcamIframe#17]
When attempting to use this application Twitch greets me with the following error on the embed screen within octoprint:

Whoops! This embed is misconfigured.

(Developers: Please check your browser console for more information)

**Comment by DKAY15** [comment]
Upon further review, it appears that twitch has changed the requirements for using embeds and you now need to also list the parent.  Not so sure this application will work any longer as we do not have an external IP for octoprint - Unless I am misunderstanding this issue?

**Comment by jneilliii** [comment]
Yeah, there's nothing I can do to resolve what they allow and don't allow. I covered this in my RTSPStreamer plugin [here](https://github.com/jneilliii/OctoPrint-RTMPStreamer#octoprint-rtmpstreamer). Basically if you don't have a fully qualified domain name to use for that parent field you can't get it to embed. You could use octoeverywhere to give you that FQDN as long as you access OctoPrint from the xxxx.octoeverywhere.com address though, and use that in the parent setting.
