### ISSUE TITLE
Need help to setup my cam

### ISSUE THREAD

**Issue by lanchuske** [jneilliii/OctoPrint-WebcamIframe#18]
I am getting an error saying that the URL is incorrect but I am able to reach the camera from internet in the same browser I use octoprint.
here is my cam http://lanchuske-30167.portmap.host:42151/
here my config screenshot
![image](https://user-images.githubusercontent.com/84111690/118066703-ca799800-b364-11eb-945b-e8610b28e75a.png)

**Comment by jneilliii** [comment]
When accessing your octoprint instance are you using `https://` or `http://`? This type of issue can happen where the browser will block access to embedding the webpage from an unsecure website if you are accessing octoprint over a secure `https://` connection. The only other reason I can think of it is the other site doesn't allow embedding into an iframe. This is something that some sites do, ie google.com.

**Comment by lanchuske** [comment]
Thanks for your response. I am accessing OctoPrint from HTTP:// 
Should be the iframe issue and I will investigate.
Thanks again
