### ISSUE TITLE
Suggestion to sandbox the iframe

### ISSUE THREAD

**Issue by prawnz** [jneilliii/OctoPrint-WebcamIframe#19]
Not an issue just a suggestion. Following https://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/
I would recommend to update have the iframe have the following attribute
`sandbox="allow-same-origin allow-scripts allow-popups allow-forms"`

**Comment by jneilliii** [comment]
Seems too limiting, what's the point and couldn't it potentially break camera streams?
