### ISSUE TITLE
Xiaomi Xiaofang hack

### ISSUE THREAD

**Issue by JeedHome44** [jneilliii/OctoPrint-WebcamIframe#2]
Hi,

I want to use your plugin to Octoprint to see my Xiaofang hack in Octoprint.
I don't find configuration where i can note url, login and password of my RTSP MJPEG.

Can you say me where i have to note that?
I don't find it in Webcam setting!

Thank you

**Comment by jneilliii** [comment]
Unfortunately, I don't think an RTSP stream will work within an iframe on it's own.  You may want to look into the deep discussion we have going on in the community forum about this over [here](https://community.octoprint.org/t/wyze-cam-v2-support/6651).
