### ISSUE TITLE
Great idea

### ISSUE THREAD

**Issue by wjflier** [jneilliii/OctoPrint-WebcamIframe#20]
This is a good idea but need a hell of a lot more info to be useful.  I've tried a number of time with several different cameras with no success.  Maybe more detailed instructions would help/

**Comment by jneilliii** [comment]
~~The plugin assumes you have multiple streaming sources already configured and available. Recommend checking out the below link if you want to do that with a default octopi image.~~

https://community.octoprint.org/t/setting-up-multiple-webcams-in-octopi-the-right-way/32669?u=jneilliii

**Comment by jneilliii** [comment]
Sorry, was thinking about a different plugin of mine when I said that. The plugin basically is just for using a web interface supplied by an IP camera for example to allow showing it within the OctoPrint interface. 

Maybe the [configuration ](https://github.com/jneilliii/OctoPrint-WebcamIframe#configuration)section helps explain better?

**Comment by wjflier** [comment]
Yeah, that's what I've been trying.  An EasyN ip cam with a simple "http:// 192.168.1.xxx/monitor2.htm" is the cam page,  but can't configure it to work.

**Comment by jneilliii** [comment]
You might be running into a browser security issue, depending on the server that supplies that page. If you open developer tools in your browser (F12) and look at the console tab are there any errors related to CORS or the like when you load the tab?

**Comment by wjflier** [comment]
"Page lacks the HTML doctype, thus triggering quirks mode"  Make any sense?

**Comment by jneilliii** [comment]
Not the error I was expecting. Nothing else red on initial page load?

**Comment by wjflier** [comment]
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform  only other error

**Comment by wjflier** [comment]
For now the first page of the cam loads but nothing after.
![image](https://user-images.githubusercontent.com/8867508/174288359-73027cda-d2d9-442a-9082-c0089dd19e15.png)

**Comment by wjflier** [comment]
Also tried a wyze cam pan set to Rtsp.  No joy there either.

**Comment by jneilliii** [comment]
Yeah, rtsp is no starter as that doesn't load natively into an iframe. If you want that I recommend something like [this](https://gist.github.com/jneilliii/fb40f42d16887649b58699f002fe48ec) instead. The plugin definitely seems to be working because the page is loading. I can't control what that page allows you to do and not do while embedded in an iframe.

**Comment by wjflier** [comment]
Appreciate it.  Probably go to usb cam and be done with it.  I'll use the ip cam as a second to keep an eye on the whole machine as it has ptz to scan.
