### ISSUE TITLE
Plugin doesn't work with the new camera stack

### ISSUE THREAD

**Issue by Ethan-C-Honzik** [jneilliii/OctoPrint-WebcamIframe#22]
The new camera stack for octoprint still uses mjpeg in the control tab which utilizes a lot of bandwith. It does however host a webrtc endpoint that utilizes h264. I was hoping to use this plugin to display the h264 webrtc in the control tab but the classic webcam seems to override the plugin. 
Is there a fix available for this?

**Comment by jneilliii** [comment]
you might want to check out https://github.com/cp2004/OctoPrint-CameraStreamer-Control.

**Comment by jneilliii** [comment]
technically this is an issue with 1.9.0, and duplicate of #21
