### ISSUE TITLE
Benefits?

### ISSUE THREAD

**Issue by SoLongSidekick** [jneilliii/OctoPrint-WebcamIframe#4]
Hey, so this isn't an issue so sorry for posting this here I just didn't know where else to put it. What are the benefits of running the webcam this way as opposed to stock? Thanks in advance.

**Comment by jneilliii** [comment]
Check out the discussion [here](https://community.octoprint.org/t/webcam-iframe-plugin-why/20666). It's really for ip cameras that don't support mjpeg streams.
