### ISSUE TITLE
Stream Renders Even in Background

### ISSUE THREAD

**Issue by cbc02009** [jneilliii/OctoPrint-WebcamIframe#6]
Plugin continues to render stream even when browser is minimized or switched away from, wasting resources on the client device.

Not sure if this is possible, but it would be awesome if the plugin could stop rendering the video when not actively being viewed by the user. This would really help the battery life on my poor old laptop.

**Comment by jneilliii** [comment]
I do know this is possible, as the default webcam image does this. I'll see what I can do.

**Comment by jneilliii** [comment]
Just released an update that should resolve this for you.

**Comment by cbc02009** [comment]
Works great! Thank you!
