### ISSUE TITLE
Opera shows error "abount: protocol

### ISSUE THREAD

**Issue by Spooky-Wookie** [jneilliii/OctoPrint-WebcamIframe#8]
In the actual version Opera shows an error when loading the dashboard with the iframe for the time:
"Unknown protocol, the is no program installed for opening the "abount:" protocol.

I located the problem in the "octoprint_webcam_iframe/static/js/webcam_iframe.js" line 15 pos 100

Changed the "abount:blank" to "about:blank" fixes this behaviour of Opera.

Other browser don't show an error as far as i can test it

**Comment by jneilliii** [comment]
Thanks, just fixed that and pushed an update.
