### ISSUE TITLE
Can´t install Plug in via several ways

### ISSUE THREAD

**Issue by dikgrax** [jneilliii/OctoPrint-WebcamIframe#9]
Hello jneilliii,

first of all thanks for your work.
I´m very new to Octoprint and Github but managed to get everything working fine.

But now I have some trouble to install your Iframe plug in to Octoprint. I tried severel routes, via Plugin Manager repository (installation freezes), via Url (freezes also), via file (diferrent naming?) and also via Putty (There seems to be an issue with the file (file not found?) 

Via repository the systems tries to load the "master.zip" but when I download the file its named "OctoPrint-WebcamIframe-master.zip"
Have you renamed something?

I´m sorry that I can´t get you more details but would appreciate some help.

kindest regards

Dik Grax

**Comment by jneilliii** [comment]
Yeah, assuming you're using OctoPrint it should just install from the Plugin Manager. Otherwis the following manual command via SSH (assuming you're using OctoPi). Don't do while printing!

```
~/oprint/bin/pip install https://github.com/jneilliii/OctoPrint-WebcamIframe/archive/master.zip
sudo service octoprint restart
```

**Comment by dikgrax** [comment]
Thank you a thousand times. Now it worked!
Great work!

Thank you again :-)
